POST http://localhost:4000/register HTTP/1.1
content-type: application/json

{
	"username": "User Admin",
	"email": "paokspaos@gmail.com",
	"telegramNumber": "5518999999999",
	"password": "adminUSER!123"
}
