POST http://localhost:4000/stripe/create-portal-session HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJiNTVmOTA5ZC00MDZhLTQwZjUtYjk1Ny1lZmY2MmQ4MDk0OWIiLCJpYXQiOjE2OTQ4ODUyNjJ9.enEJTl_uT_0Ra1sExNcHCmkiLUU9Wk3qKcrCLTZNAKM

{
	"session_id": "cs_test_a1KhhE52pXYCWkOQfS2xvxpy6zJwbZGzxXEJMteEVhvkc8Ee4ZGBaWYAGI"
}
